apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /etc/odoo /var/lib/odoo /mnt/extra-addons && chmod -R 777 /etc/odoo /var/lib/odoo /mnt/extra-addons']
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /etc/odoo
        - name: lib-odoo-persistent-storage
          mountPath: /var/lib/odoo
        - name: extra-addons-persistent-storage
          mountPath: /mnt/extra-addons
      containers:
      - name: odoo
        image: odoo:14.0  
        ports:
        - name: odoo
          containerPort: 8069
        env:
        - name: USER
          value: toto
        - name: HOST
          value: postgres
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo
              key: PASSWORD
        - name: DATABASE
          value: odoo  
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /etc/odoo
        - name: lib-odoo-persistent-storage
          mountPath: /var/lib/odoo
        - name: extra-addons-persistent-storage
          mountPath: /mnt/extra-addons
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "2"
      volumes:
      - name: odoo-persistent-storage
        hostPath:
          path: /data_k8s/config 
          type: Directory
      - name: extra-addons-persistent-storage
        hostPath:
          path: /data_k8s/addons  
          type: Directory
      - name: lib-odoo-persistent-storage
        persistentVolumeClaim:
          claimName: odoo-pvc
